const { NodeGraphic, getNewNodeId } = require('./classes')
const NODE_RADIUS = 30

data = {
  selectedStart: "Arad",
  selectedGoals: new Set(["Bucuresti"]),
  nodes: {
    "Oradea": new NodeGraphic(getNewNodeId(), 200, 50, "Oradea", NODE_RADIUS, 380),
    "Zerind": new NodeGraphic(getNewNodeId(), 100, 100, "Zerind", NODE_RADIUS, 374),
    "Arad": new NodeGraphic(getNewNodeId(), 150, 200, "Arad", NODE_RADIUS, 366),
    "Timisoara": new NodeGraphic(getNewNodeId(), 200, 300, "Timisoara", NODE_RADIUS, 329),
    "Lugoj": new NodeGraphic(getNewNodeId(), 330, 300, "Lugoj", NODE_RADIUS, 244),
    "Mehadia": new NodeGraphic(getNewNodeId(), 330, 400, "Mehadia", NODE_RADIUS, 241),
    "Drobeta": new NodeGraphic(getNewNodeId(), 330, 500, "Drobeta", NODE_RADIUS, 242),
    "Craiova": new NodeGraphic(getNewNodeId(), 480, 500, "Craiova", NODE_RADIUS, 160),
    "Sibiu": new NodeGraphic(getNewNodeId(), 500, 200, "Sibiu", NODE_RADIUS, 253),
    "RamnicuValcea": new NodeGraphic(getNewNodeId(), 550, 300, "RamnicuValcea", NODE_RADIUS, 193),
    "Pitesti": new NodeGraphic(getNewNodeId(), 600, 400, "Pitesti", NODE_RADIUS, 98),
    "Fagaras": new NodeGraphic(getNewNodeId(), 650, 220, "Fagaras", NODE_RADIUS, 178),
    "Bucuresti": new NodeGraphic(getNewNodeId(), 750, 450, "Bucuresti", NODE_RADIUS, 0),
    "Giurgiu": new NodeGraphic(getNewNodeId(), 700, 550, "Giurgiu", NODE_RADIUS, 77),
    "Urziceni": new NodeGraphic(getNewNodeId(), 830, 400, "Urziceni", NODE_RADIUS, 80),
    "Hirsova": new NodeGraphic(getNewNodeId(), 950, 400, "Hirsova", NODE_RADIUS, 77),
    "Eforie": new NodeGraphic(getNewNodeId(), 950, 550, "Eforie", NODE_RADIUS, 161),
    "Vaslui": new NodeGraphic(getNewNodeId(), 880, 230, "Vaslui", NODE_RADIUS, 199),
    "Iasi": new NodeGraphic(getNewNodeId(), 830, 130, "Iasi", NODE_RADIUS, 226),
    "Neamt": new NodeGraphic(getNewNodeId(), 750, 100, "Neamt", NODE_RADIUS, 234)
  },
  edges: [
    ["Oradea", "Zerind", 71],
    ["Oradea", "Sibiu", 151],
    ["Zerind", "Arad", 75],
    ["Zerind", "Oradea", 71],
    ["Arad", "Zerind", 75],
    ["Arad", "Sibiu", 140],
    ["Arad", "Timisoara", 118],
    ["Timisoara", "Arad", 118],
    ["Timisoara", "Lugoj", 111],
    ["Lugoj", "Timisoara", 111],
    ["Lugoj", "Mehadia", 70],
    ["Mehadia", "Lugoj", 70],
    ["Mehadia", "Drobeta", 75],
    ["Drobeta", "Mehadia", 75],
    ["Drobeta", "Craiova", 120],
    ["Craiova", "Drobeta", 120],
    ["Craiova", "RamnicuValcea", 146],
    ["Craiova", "Pitesti", 138],
    ["RamnicuValcea", "Craiova", 146],
    ["RamnicuValcea", "Pitesti", 97],
    ["RamnicuValcea", "Sibiu", 80],
    ["Sibiu", "Oradea", 151],
    ["Sibiu", "RamnicuValcea", 80],
    ["Sibiu", "Fagaras", 99],
    ["Fagaras", "Sibiu", 99],
    ["Fagaras", "Bucuresti", 211],
    ["Pitesti", "RamnicuValcea", 97],
    ["Pitesti", "Bucuresti", 101],
    ["Bucuresti", "Pitesti", 101],
    ["Bucuresti", "Fagaras", 211],
    ["Bucuresti", "Giurgiu", 90],
    ["Bucuresti", "Urziceni", 85],
    ["Giurgiu", "Bucuresti", 90],
    ["Urziceni", "Bucuresti", 85],
    ["Urziceni", "Hirsova", 98],
    ["Urziceni", "Vaslui", 142],
    ["Hirsova", "Urziceni", 98],
    ["Hirsova", "Eforie", 86],
    ["Eforie", "Hirsova", 86],
    ["Vaslui", "Urziceni", 142],
    ["Vaslui", "Iasi", 92],
    ["Iasi", "Vaslui", 92],
    ["Iasi", "Neamt", 87],
    ["Neamt", "Iasi", 87]
  ]
}
module.exports = data